# Plugins loaded upon launching neovim

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
command DB Denite buffer
command DF Denite file_rec
command DG Denite grep
command DL Denite line
call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
call denite#custom#map('insert', '<leader>s', '<denite:do_action:split>', 'noremap')
call denite#custom#map('insert', '<Leader>v', '<denite:do_action:vsplit>', 'noremap')
call denite#custom#map('insert', '<Leader>t', '<denite:do_action:tabopen>', 'noremap')
'''

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# General Editing
[[plugins]]
repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'othree/eregex.vim'
[[plugins]]
repo = 'wesQ3/vim-windowswap'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=236
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=236
'''

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
map <S-r> :GitGutterAll<CR>
'''
