# Plugins loaded lazily

# Markdown
[[plugins]]
on_ft = ['markdown','mkd']
repo = 'plasticboy/vim-markdown'
hook_add = '''
let g:vim_markdown_conceal = 0
'''
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']
hook_add = '''
autocmd FileType markdown setlocal tabstop=3 softtabstop=3 shiftwidth=3 nospell
'''
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']

# Python

# Go

# Frontend
[[plugins]]
on_ft = ['html', 'vue']
repo = 'mattn/emmet-vim'
hook_add = '''
autocmd FileType vue syntax sync fromstart
'''
[[plugins]]
on_ft = ['vue']
repo = 'posva/vim-vue'
